### ISSUE TITLE
Build Project with Delphi Tokyo failed

### ISSUE THREAD

**Issue by EdmundPfundstein** [marlonnardi/JsonToDelphi#3]
Hallo Marlon Nardi,
this is a great software and I use the version of Jens Borrisholt. 
To get your corrections and improvements, I tried to get the FMX project JsonToDelphiClass.dproj running with Delphi Tokyo. 

Some issues I corrected for me:

1. Search path I had to add ..\
2. ToString(True) of TStringBuilder I changed to ToString().
3. aJsonValue.AsType<string> I changed to aJsonValue.Value
4. local var name  not supported I changed it.
5. Pkg.Json.Visualizer.pas was missing, I get it from https://github.com/JensBorrisholt/Delphi-JsonToDelphiClass/tree/master/Components
6. Pkg.Json.StubField was missing in uMainForm

Maybe you could correct this?

Greetings Edmund Pfundstein

**Comment by marlonnardi** [comment]
Fixed
