### ISSUE TITLE
Object serializing from Json string: "invalid time string"

### ISSUE THREAD

**Issue by MiltonSonoda** [marlonnardi/JsonToDelphi#6]
Datetime in format "2022-07-05T12:53:18+00:00"
causes an error message: "invalid time string"
if I remove time part "2022-07-05T12:53:18" its fine.

**Comment by MiltonSonoda** [comment]
Delphi version.

**Comment by MiltonSonoda** [comment]
Delphi version.

**Comment by marlonnardi** [comment]
Hi @MiltonSonoda, Thanks for the feedback, I will look into your case.

**Comment by MiltonSonoda** [comment]
.
